alerts:
  - rule: DEPLOYMENT_FAILED

services:
  - name: trio-server
    github:
      branch: sobe-nova-visu-a-pedido-dos-fans
      deploy_on_push: true
      repo: brunocsilva41/TrioOnline
    run_command: node start.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
