apiVersion: v1
kind: Service
metadata:
  name: game-server-service
  namespace: ns-game-servers
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2567
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-server-ingress
  namespace: ns-game-servers
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # Sticky Sessions Configuration
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$binary_remote_addr"
spec:
  rules:
  - host: game.trioonline.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-server-service
            port:
              number: 80
